redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

service:
  http:
    type: LoadBalancer
    port: 3000
    clusterIP: None
    loadBalancerIP:
    sessionAffinity: ClientIP
  ssh:
    type: LoadBalancer
    port: 22
    clusterIP: None
    sessionAffinity: ClientIP
